<h1>Python - Exceptions</h1>
<p>Tasks being handled:</p>
<ol>
<li>Safe list printing</li>
<li>Safe printing of an integers list</li>
<li>Print and count integers</li>
<li>Integers division with debug</li>
<li>Divide a list</li>
<li>Raise exception</li>
<li>Raise a message</li>
<li>Safe integer print with error message</li>
<li>Safe function</li>
<li>ByteCode -> Python #4</li>
<li>CPython #2: PyFloatObject</li>
</ol>
